Atualizado currículo
reprograma/on6-xp-s16-carreira pull request #11
Opened 2020-11-27 20:27 UTC by andreianet

2020-12-08 19:26 UTC, flaviadessoldi requested changes
Que tal deixa r a parte "o que eu quero" mais objetiva?
Geralmente essa é a primeira coisa que os recrutadores Lêem num curriculo, é seu objetivo profissional, seria mais interessante que você fosse mais direta no que deseja atuar e deixar a parte de migrar de área para o texto sobre você. Que tal se ao invés de: "o_que_eu_quero": "Migrar de cargo, ou seja, de Analista de Suporte à Desenvolvedora, tendo a oportunidade de contribuir com o crescimento da empresa que confiar no meu trabalho.", você tentar deixar mais claro que quer ser uma desenvolvedora e em qual area deseja atuar? Por exemplo: 

"o_que_eu_quero": "Ser uma desenvolvedora backend contribuindo com soluções que impactam positivamente a vida das pessoas", ou algo do tipo, sabe? Não precisa ser exatamente a minha sugestão. Ser bem assertiva em qual é seu objetivo profissional pode aumentar em muito as chances de ser chamada pra uma entrevista.

O que acha?

2020-12-09 21:42 UTC, andreianet commented
Corrigido e atualizado. Obrigada Flávia!

2020-12-13 00:14 UTC, flaviadessoldi approved these changes

2020-12-13 00:14 UTC, flaviadessoldi approved these changes

2020-12-13 00:14 UTC, merged