Atualizando currículo
reprograma/on6-xp-s16-carreira pull request #33
Opened 2020-11-28 02:13 UTC by shaiennes

2020-12-08 22:16 UTC, flaviadessoldi requested changes
Perfeita! Só precisa corrigir a palavra Apaixonada na parte 'um pouco sobre mim' está escrito Apoixona

2020-12-09 06:02 UTC, shaiennes commented
> Perfeita! Só precisa corrigir a palavra Apaixonada na parte 'um pouco sobre mim' está escrito Apoixona

Muito Grata pelo feedback, Flávia! Ajustes feitos com sucesso.🚀

2020-12-09 13:20 UTC, flaviadessoldi requested changes
Oi Shay!

Não seria Apaixonada a palavra? Você corrigiu para Apaixona porém acredito que pelo contexto da frase você quis dizer Apaixonada, não? Dá uma olhadinha :)

2020-12-09 20:53 UTC, shaiennes commented
Sim, Flávia!

Você tem toda razão.

Obrigada novamente! <3

<https://signtr.online/click?redirect=https%3A%2F%2Fdrive.google.com%2Fdrive%2Fu%2F1%2Ffolders%2F1a50k9116qQttgY58pxcSWHzXQ7vX03e9&dID=1607547218478>
*SHAIENE
BARBOSA*
+55 48 9 9165-1968
<https://signtr.online/click?redirect=http%3A%2F%2Fapi.whatsapp.com%2Fsend%3F1%3Dpt_BR%26phone%3D5548991651968&dID=1607547218478&linkName=+55
48 9 9165-1968>


Em qua., 9 de dez. de 2020 às 10:20, Flavia Dessoldi <
notifications@github.com> escreveu:

> *@flaviadessoldi* requested changes on this pull request.
>
> Oi Shay!
>
> Não seria Apaixonada a palavra? Você corrigiu para Apaixona porém acredito
> que pelo contexto da frase você quis dizer Apaixonada, não? Dá uma
> olhadinha :)
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/reprograma/on6-xp-s16-carreira/pull/33#pullrequestreview-548173562>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AQRNO6IENA7VVAG3QDOVK5TST52RFANCNFSM4UFPGS3Q>
> .
>

2020-12-13 00:16 UTC, flaviadessoldi approved these changes

2020-12-13 00:16 UTC, flaviadessoldi approved these changes

2020-12-13 00:16 UTC, merged